
<left>
    <img src="http://people.ufpr.br/~emilio/figuras/img5.jpg" width="300" alt="PPGOLD Data Science: INTRO"  />
</left>

# *Python - Aula 04*

# NUMPY

In [2]:
import numpy as np
np.__version__

'1.24.3'

## Primeiro Vetor

In [4]:
nparray = np.array([1,2,3])
nparray.dtype

dtype('int64')

In [5]:
nparray.size

3

In [6]:
nparray.shape

(3,)

## Alocação de Memória 

In [55]:
nparray.itemsize

8

In [56]:
nparray.nbytes

24

### Tempo para alocacão

In [9]:
%timeit pythonList = [i for i in range(10000)]

139 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
%timeit npList = np.arange(10000)

2.52 µs ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Diferentes formas de inicializar o vetor

In [11]:
np.arange(10) # vetor enumerado

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3,10) # vetor enumerado

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2,10,2) # vetor enumerado com passo de 2

array([2, 4, 6, 8])

In [19]:
np.ones(5) # vetor de UNS

array([1., 1., 1., 1., 1.])

In [20]:
np.zeros(5)# vetor de ZEROS

array([0., 0., 0., 0., 0.])

In [57]:
np.empty(5)  # vetor vazio (o valor de cada item é lixo)

array([1., 1., 1., 1., 1.])

In [60]:
np.eye(4) # Matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Espaço linear entre dois pontos

In [61]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Sistemas Lineares

In [40]:
A = np.array([[1, 2], [3, 5]])
b = np.array([-1, -2])
x = np.linalg.solve(a, b)

In [41]:
x

array([ 1., -1.])

## Produto de Vetores

In [45]:
np.dot(A, x)

array([-1., -2.])

In [46]:
b

array([-1, -2])

### Função allclose (todos próximos)

In [42]:
np.allclose(np.dot(A, x), b)

True

# Biblioteca de álgebra linear

In [47]:
from numpy import linalg as LA

## Matriz inversa

In [50]:
LA.inv(A

array([[-5.,  2.],
       [ 3., -1.]])

## Determinante

In [65]:
LA.det(A)

-1.0000000000000004

## Auto-valores e Auto-vetores

In [48]:
LA.eigvals(A)

array([-0.16227766,  6.16227766])

In [63]:
w, v = LA.eig(A)
print(w)
print(v)

[-0.16227766  6.16227766]
[[-0.86460354 -0.36126098]
 [ 0.50245469 -0.93246475]]


# Decomposições
## Cholesky

Tem uma similar no SciPy

scipy.linalg.cholesky

In [70]:
A = np.array([[2, 1], [1, 2]])
print(LA.det(A))
L = np.linalg.cholesky(A)

2.9999999999999996


In [71]:
L

array([[1.41421356, 0.        ],
       [0.70710678, 1.22474487]])

## QR

Similar function in SciPy

scipy.linalg.qr


In [72]:
q, r = np.linalg.qr(a)

In [73]:
q

array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]])

In [74]:
r

array([[-3.16227766, -5.37587202],
       [ 0.        , -0.31622777]])

## References

* https://towardsdatascience.com/numpy-crash-course-zero-to-hero-c1788a8a48ac
* https://jakevdp.github.io/PythonDataScienceHandbook/
* https://numpy.org/doc/1.24/reference/
* https://numpy.org/doc/1.24/reference/routines.linalg.html


## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2023-05-10  | 0.9  | <a href="https://www.linkedin.com/in/eduardopecora/" target="_blank">Eduardo Pécora</a> |  Initial development |

<hr>